name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]  # main 브랜치에 푸시될 때 배포
  workflow_dispatch:     # 수동 실행도 가능하게 함

permissions:
  contents: write         # gh-pages 브랜치 푸시 권한

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'  # 안정 버전 사용

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --base-href "/my_tuils/"  # 리포지토리 이름에 맞게 설정

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_UTILS_KEY }}  # GitHub 기본 제공 토큰
          publish_dir: ./build/web                   # 빌드 결과물 폴더